---
title: City of Austin Pages
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://pages.austintexas.io
markdown: kramdown
permalink: pretty
exclude:
- api
- bin
- circle.yml
- Gemfile
- vendor
